CREATE TABLE [dbo].[OrderItem]
(
	[OrderItemId] INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    [OrderId] INT NOT NULL FOREIGN KEY REFERENCES [Order](OrderID),
    [ISBN] VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES [Book](ISBN), 
    [Qty] INT NOT NULL, 
    [Price] DECIMAL(10, 2) NOT NULL
)
